from typing import Any

from deployment.targets import DeploymentProfile, resolve_profile_defaults


def generate_env_example(env_vars: list[str], secret_keys: list[str] | None = None) -> str:
    """Deterministic .env.example text - real key names, empty values (never
    a real secret in a generated template).
    """
    lines = ["# Auto-generated by AFOS Deployment Generator", "# Fill in real values - never commit actual secrets", ""]
    for key in env_vars:
        lines.append(f"{key}=")
    if secret_keys:
        lines.append("")
        lines.append("# Secrets (fetch from your secret manager, do not hardcode)")
        for key in secret_keys:
            lines.append(f"{key}=")
    return "\n".join(lines) + "\n"


def generate_secrets_template(secret_keys: list[str]) -> dict[str, str]:
    return {key: "" for key in secret_keys}


def generate_variables_template(env_vars: list[str]) -> dict[str, str]:
    return {key: "" for key in env_vars}


def generate_runtime_config(project_name: str, profile: str = DeploymentProfile.PRODUCTION, port: int = 8000) -> dict[str, Any]:
    defaults = resolve_profile_defaults(profile)
    return {"project_name": project_name, "profile": profile, "port": port, **defaults}
