import json
import threading
import time
import uuid
from pathlib import Path
from typing import Any


class DeploymentRecordStatus:
    PENDING = "pending"
    DEPLOYED = "deployed"
    FAILED = "failed"
    ROLLED_BACK = "rolled_back"


_ROLLBACK_COMMANDS: dict[str, str] = {
    "github": "gh workflow run ci-cd.yml --ref {version}",
    "docker": "docker build -t {project_name}:{version} . && docker run -d --name {project_name} {project_name}:{version}",
    "docker_compose": "docker compose up -d --build",
    "vercel": "vercel rollback {version}",
    "railway": "railway up --detach",
    "render": "render deploys create --commit {version}",
    "flyio": "flyctl deploy --image {project_name}:{version}",
    "kubernetes": "kubectl rollout undo deployment/{project_name} --to-revision={version}",
}


def generate_rollback_script(target: str, project_name: str, version: str) -> str:
    """Deterministic, per-target rollback shell script text - one command per
    target, never duplicating any real infra agent's own deploy logic (this
    is a plan a human or CI job runs, not an execution engine).
    """
    command = _ROLLBACK_COMMANDS.get(target, f"echo 'no known rollback command for target {target}'")
    command = command.format(project_name=project_name, version=version)
    return (
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n\n"
        f"# Rollback script for {project_name} on {target}, generated by AFOS Deployment Generator\n"
        f"# Target version: {version}\n\n"
        f"{command}\n"
    )


class DeploymentHistoryStore:
    """Thread-safe, append-only deployment history - the record every
    rollback operates against. A rollback never mutates a past record;
    it appends a NEW record (rollback_of pointing at the target) whose own
    version/artifacts match the one being rolled back to - "redeploy a known-
    good version" is the same real-world rollback semantic every one of the 8
    target platforms actually uses.
    """

    def __init__(self) -> None:
        self._lock = threading.RLock()
        self._deployments: dict[str, dict[str, Any]] = {}
        self._order: list[str] = []

    def record_deployment(
        self,
        venture_id: str,
        target: str,
        profile: str,
        version: str,
        artifacts_summary: dict[str, Any] | None = None,
        status: str = DeploymentRecordStatus.DEPLOYED,
        rollback_of: str | None = None,
        deployment_id: str | None = None,
    ) -> dict[str, Any]:
        with self._lock:
            did = deployment_id or str(uuid.uuid4())
            entry = {
                "deployment_id": did, "venture_id": venture_id, "target": target, "profile": profile,
                "version": version, "artifacts_summary": artifacts_summary or {}, "status": status,
                "rollback_of": rollback_of, "created_at": time.time(),
            }
            self._deployments[did] = entry
            self._order.append(did)
            return dict(entry)

    def get_deployment(self, deployment_id: str) -> dict[str, Any] | None:
        with self._lock:
            entry = self._deployments.get(deployment_id)
            return dict(entry) if entry is not None else None

    def list_deployments(
        self,
        venture_id: str | None = None,
        target: str | None = None,
        status: str | None = None,
        limit: int | None = None,
        offset: int = 0,
    ) -> list[dict[str, Any]]:
        with self._lock:
            items = [dict(self._deployments[did]) for did in reversed(self._order)]
        if venture_id is not None:
            items = [d for d in items if d["venture_id"] == venture_id]
        if target is not None:
            items = [d for d in items if d["target"] == target]
        if status is not None:
            items = [d for d in items if d["status"] == status]
        items = items[offset:]
        if limit is not None:
            items = items[:limit]
        return items

    def get_current(self, venture_id: str, target: str) -> dict[str, Any] | None:
        deployed = self.list_deployments(venture_id=venture_id, target=target, status=DeploymentRecordStatus.DEPLOYED)
        return deployed[0] if deployed else None

    def mark_status(self, deployment_id: str, status: str) -> bool:
        with self._lock:
            entry = self._deployments.get(deployment_id)
            if entry is None:
                return False
            entry["status"] = status
            return True

    def rollback_to(self, venture_id: str, target: str, deployment_id: str) -> dict[str, Any] | None:
        target_record = self.get_deployment(deployment_id)
        if target_record is None or target_record["venture_id"] != venture_id or target_record["target"] != target:
            return None
        current = self.get_current(venture_id, target)
        if current is not None and current["deployment_id"] != deployment_id:
            self.mark_status(current["deployment_id"], DeploymentRecordStatus.ROLLED_BACK)
        return self.record_deployment(
            venture_id=venture_id, target=target, profile=target_record["profile"], version=target_record["version"],
            artifacts_summary=target_record["artifacts_summary"], status=DeploymentRecordStatus.DEPLOYED, rollback_of=deployment_id,
        )

    def clear(self) -> None:
        with self._lock:
            self._deployments.clear()
            self._order.clear()

    def size(self) -> int:
        with self._lock:
            return len(self._deployments)

    def save_to_disk(self, path: str | Path) -> None:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with self._lock:
            path.write_text(json.dumps({"deployments": self._deployments, "order": self._order}, indent=2), encoding="utf-8")

    def load_from_disk(self, path: str | Path) -> bool:
        path = Path(path)
        if not path.exists():
            return False
        data = json.loads(path.read_text(encoding="utf-8"))
        with self._lock:
            self._deployments = data.get("deployments", {})
            self._order = data.get("order", [])
        return True


_default_store = DeploymentHistoryStore()


def get_default_deployment_history_store() -> DeploymentHistoryStore:
    return _default_store


def set_default_deployment_history_store(store: DeploymentHistoryStore) -> None:
    global _default_store
    _default_store = store


def reset_default_deployment_history_store() -> None:
    global _default_store
    _default_store = DeploymentHistoryStore()
